GRANT CONNECT, RESOURCE TO UPNEXT;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO UPNEXT;
ALTER USER UPNEXT QUOTA UNLIMITED ON USERS;

GRANT CREATE TRIGGER TO UPNEXT;

-- as SYS in the correct PDB (e.g., XEPDB1)
GRANT CREATE VIEW TO UPNEXT;

GRANT CREATE PROCEDURE TO UPNEXT;